/**
 * N8n workflow types and utilities
 * The actual workflow JSON generation is handled by generateN8nWorkflowJSON() in ai.ts
 * This file provides type definitions and validation utilities
 */

export interface N8nNode {
  parameters: Record<string, any>;
  type: string;
  typeVersion: number | number[];
  position: [number, number];
  id: string;
  name: string;
  credentials?: Record<string, { id: string; name: string }>;
}

export interface N8nConnection {
  [nodeName: string]: {
    main: Array<Array<{ node: string; type: string; index: number }>>;
  };
}

export interface N8nWorkflow {
  name: string;
  nodes: N8nNode[];
  connections: N8nConnection;
  active: boolean;
  settings: {
    executionOrder: string;
    binaryMode: string;
    availableInMCP: boolean;
  };
  pinData: Record<string, any>;
}

/**
 * Validate that an n8n workflow is properly structured
 * Returns validation status with detailed error messages
 */
export function validateN8nWorkflow(workflow: any): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  if (!workflow.name) errors.push('Workflow must have a name');
  if (!Array.isArray(workflow.nodes)) errors.push('Workflow must have nodes array');
  if (!workflow.connections) errors.push('Workflow must have connections object');
  if (workflow.nodes && workflow.nodes.length === 0) errors.push('Workflow must have at least one node');

  // Validate nodes
  if (Array.isArray(workflow.nodes)) {
    workflow.nodes.forEach((node: N8nNode, index: number) => {
      if (!node.type) errors.push(`Node ${index} must have a type`);
      if (!node.id) errors.push(`Node ${index} must have an id`);
      if (!node.name) errors.push(`Node ${index} must have a name`);
      if (!Array.isArray(node.position) || node.position.length !== 2) {
        errors.push(`Node ${index} must have valid position [x, y]`);
      }
    });
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

/**
 * Ensure workflow has default settings and proper structure
 * Used to normalize workflows generated by AI
 */
export function ensureWorkflowDefaults(workflow: any): N8nWorkflow {
  return {
    name: workflow.name || 'Untitled Workflow',
    nodes: workflow.nodes || [],
    connections: workflow.connections || {},
    active: workflow.active ?? false,
    settings: {
      executionOrder: 'v1',
      binaryMode: 'separate',
      availableInMCP: false,
      ...workflow.settings,
    },
    pinData: workflow.pinData || {},
  };
}



